Update FW build scripts
Change-Id: I60b0b371f4c9ab26fa31638bf89972d87500b8bc

diff --git a/building/fw-build-recent b/building/fw-build-recent
--- a/building/fw-build-recent
+++ b/building/fw-build-recent
@@ -8,6 +8,8 @@
 # Original author: MarkS 2013-08-14
 
 program_name=$(basename "$0")
+PLATFORM=$(test `arch` = x86_64 && echo x64 || echo x86)
+
 minutes_ago=${1:-30}
 changed_files=$(find Src -mmin -$minutes_ago -name \*.cs)
 changed_dirs=$(for file in $changed_files; do
@@ -19,7 +21,7 @@ changed_dirs_with_projects=$(for dir in $changed_dirs; do
 	[ -e "$dir"/../*.csproj ] && (cd "$dir"/.. && pwd)
 done)
 /usr/bin/time -f "$program_name: Total time elapsed %E." cat <(for dir in $changed_dirs_with_projects; do
-	(. environ && cd "$dir" && xbuild || (echo "$program_name: Error building project $(basename "$dir"). Continuing ..."; sleep 5s))
+	(. environ && cd "$dir" && xbuild /p:Platform=$PLATFORM || (echo "$program_name: Error building project $(basename "$dir"). Continuing ..."; sleep 5s))
 done)
 projects=$(for dir in $changed_dirs_with_projects; do
 	basename "$dir"
